name: Export Firestore Indexes

on:
  pull_request:
    branches:
      - staging

jobs:
  export-firestore-indexes:
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: write  # Ensure the workflow has write permissions to the repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: echo "Installed firebase tool" # npm install -g firebase-tools
        
      - name: Gesture Firebase Google Auth
        # uses: google-github-actions/auth@v2
        # with:
        #   credentials_json: ${{ secrets.GESTURE_FIREBASE_SA_KEY }}
        run: echo "Gesture Firebase Google Auth"

      - name: Configure git
        run: |
          echo "Configuring git"

      - name: Pull latest changes
        run: |
          echo "Pulling latest changes"

      - name: Export Gesture Firebase Firestore Indexes
        run: |
          echo "Exported Gesture Firebase Firestore Indexes"
        
      - name: Gesture Firebase User Google Auth
        # uses: google-github-actions/auth@v2
        # with:
        #   credentials_json: ${{ secrets.GESTURE_FIREBASE_USER_SA_KEY }}
        run: echo "Gesture Firebase User Google Auth"
            
      - name: Export Gesture Firebase User Firestore Indexes
        run: |
          echo "Exported Gesture Firebase User Firestore Indexes"

      - name: Check If Firestore Index Files Have Changed
        id: git_status
        run: |
          echo "Checking if Firestore Index Files Have Changed"

      - name: Commit Firestore Indexes
        # if: env.changed == 'true'
        run: |
          echo "Committed Firestore Indexes"
