name: Deploy firebase indexes without deleting.
description: 'Deploy firebase indexes without deleting.'
inputs:
  project:
    description: 'Firebase project to deploy indexes for.'
    required: true
  path: 
    description: 'Path to the firebase project.'
    required: false
    default: './'
runs:
  using: 'composite'
  steps:
    - name: Install expect interpreter
      shell: bash
      run: |
          if ! command -v expect &> /dev/null; then
            sudo apt-get update && sudo apt-get install -y expect
          else
            echo "Expect is already installed"
          fi

    - name: Deploy Firestore Indexes
      shell: expect
      run: |
          #!/usr/bin/expect
          cd ${{ inputs.path }}
          spawn firebase deploy --project=${{ inputs.project }} --only firestore:indexes
          expect {
              "Would you like to delete these indexes? Selecting no will continue the rest of the deployment" {
                  send "N\r"
                  interact
              }
          }
