name: Branch Sync
on:
  push:
    branches:
      - production

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Opening pull request
        id: pull
        uses: sansx/sync-branches@v1.0.1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "production"
          TO_BRANCH: "staging"