name: Firebase Deploy

on:
  release:
    types: [published]
  push:
    branches:
      - staging
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy'
        required: true
        type: choice
        default: 'all'
        options:
          - 'all'
          - 'staging'
          - 'production'
      project:
        description: 'Select project to deploy'
        required: true
        type: choice
        default: 'all'
        options:
          - 'all'
          - 'gesture-firebase'
          - 'gesture-firebase-user'

jobs:
  check-access:
    runs-on: ubuntu-latest
    steps:
      - name: Check user
        uses: actions/github-script@v7
        id: my-script
        with:
          result-encoding: string
          retries: 3
          script: |
            const { data: members } = await octokit.teams.listMembers({
              team_id: 'superadmin'
            });
            return members.some(member => member.login === context.actor);

  staging-deploy:
    # Deploy only on pushes to the staging branch or when manually triggered and the staging branch is selected or all environments is selected
    if: (startsWith(github.ref, 'refs/heads/staging')) || (github.event.inputs.environment == 'all' || github.event.inputs.environment == 'staging')
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Gesture Firebase Dependencies
        run: |
          echo "Installed Gesture Firebase Dependencies"

      - name: Install Gesture Firebase User Dependencies
        run: |
          echo "Installed Gesture Firebase User Dependencies"

      - name: Install Firebase Tools
        run: echo "Intalled firebase tool" # npm install -g firebase-tools

      - name: Install Infisical CLI
        run: |
          echo "Installed Infisical CLI"

      - name: Login to Infisical and export envs
        run: |
          echo "Logged in to Infisical and exported envs"

      - name: Gesture Firebase Google Auth
        # Run only on push to staging or when gesture-firebase is selected or all projects is selected
        if: (startsWith(github.ref, 'refs/heads/staging')) ||github.event.inputs.project == 'gesture-firebase' || github.event.inputs.project == 'all'
        # uses: google-github-actions/auth@v2
        # with:
        #   credentials_json: ${{ secrets.GESTURE_FIREBASE_SA_KEY }}
        run: echo "Gesture Firebase Google Auth"

      - name: Deploy Staging Gesture Firebase Functions and Indexes
        # Deploy only on push to staging or when gesture-firebase is selected or all projects is selected
        if: (startsWith(github.ref, 'refs/heads/staging')) || github.event.inputs.project == 'gesture-firebase' || github.event.inputs.project == 'all'
        run: |
          echo "Deployed Staging Gesture Firebase Functions and Indexes"
          
      - name: Gesture Firebase User Google Auth
        # Run only on push to staging or when gesture-firebase-user is selected or all projects is selected
        if: (startsWith(github.ref, 'refs/heads/staging')) || github.event.inputs.project == 'gesture-firebase-user' || github.event.inputs.project == 'all'
        # uses: google-github-actions/auth@v2
        # with:
        #   credentials_json: ${{ secrets.GESTURE_FIREBASE_USER_SA_KEY }}
        run: echo "Gesture Firebase User Google Auth"

      - name: Deploy Staging Gesture Firebase User Functions and Indexes
        # Deploy only push to staging or when gesture-firebase-user is selected or all projects is selected
        if: (startsWith(github.ref, 'refs/heads/staging')) || github.event.inputs.project == 'gesture-firebase-user' || github.event.inputs.project == 'all'
        run: |
          echo "Deployed Staging Gesture Firebase User Functions and Indexes"
          
  production-deploy:
    # Deploy only on tagged releases to the production branch or when manually triggered and the production branch is selected or all environments is selected
    if: >
      (
        (startsWith(github.ref, 'refs/tags/gesture-firebase') || 
        startsWith(github.ref, 'refs/tags/gesture-firebase-user')) &&
        (github.event.base_ref == 'refs/heads/production' ||
        github.event.release.target_commitish == 'production')
      ) || 
      github.event.inputs.environment == 'all' || 
      github.event.inputs.environment == 'production'
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Gesture Firebase Dependencies
        # Run only on tagged release or when gesture-firebase is selected or all projects is selected
        if: startsWith(github.ref, 'refs/tags/gesture-firebase-v') || github.event.inputs.project == 'gesture-firebase' || github.event.inputs.project == 'all'
        run: |
          echo "Installed Gesture Firebase Dependencies"

      - name: Install Gesture Firebase User Dependencies
        # Run only on tagged release or when gesture-firebase-user is selected or all projects is selected
        if: startsWith(github.ref, 'refs/tags/gesture-firebase-user-v') || github.event.inputs.project == 'gesture-firebase-user' || github.event.inputs.project == 'all'
        run: |
          echo "Installed Gesture Firebase User Dependencies"

      - name: Install Firebase Tools
        run: echo "Installed firebase tool" # npm install -g firebase-tools

      - name: Install Infisical CLI
        run: |
          echo "Installed Infisical CLI"

      - name: Login to Infisical and export envs
        run: |
          echo "Logged in to Infisical and exported envs"

      - name: Gesture Firebase Google Auth
        # Run only on tagged release or when gesture-firebase is selected or all projects is selected
        if: startsWith(github.ref, 'refs/tags/gesture-firebase-v') || github.event.inputs.project == 'gesture-firebase' || github.event.inputs.project == 'all'
        # uses: google-github-actions/auth@v2
        # with:
        #   credentials_json: ${{ secrets.GESTURE_FIREBASE_SA_KEY }}
        run: echo "Gesture Firebase Google Auth"

      - name: Deploy Production Gesture Firebase Functions and Indexes
        # Deploy only on tagged release or when gesture-firebase is selected or all projects is selected
        if: startsWith(github.ref, 'refs/tags/gesture-firebase-v') || github.event.inputs.project == 'gesture-firebase' || github.event.inputs.project == 'all'
        run: |
          echo "Deployed Production Gesture Firebase Functions and Indexes"

      - name: Gesture Firebase User Google Auth
        # Run only on tagged release or when gesture-firebase-user is selected or all projects is selected
        if: startsWith(github.ref, 'refs/tags/gesture-firebase-user-v') || github.event.inputs.project == 'gesture-firebase-user' || github.event.inputs.project == 'all'
        # uses: google-github-actions/auth@v2
        # with:
        #   credentials_json: ${{ secrets.GESTURE_FIREBASE_USER_SA_KEY }}
        run: echo "Gesture Firebase User Google Auth"

      - name: Deploy Production Gesture Firebase User Functions and Indexes
        # Deploy only on tagged release or when gesture-firebase-user is selected or all projects is selected
        if: startsWith(github.ref, 'refs/tags/gesture-firebase-user-v') || github.event.inputs.project == 'gesture-firebase-user' || github.event.inputs.project == 'all'
        run: |
          echo "Deployed Production Gesture Firebase User Functions and Indexes"