name: Linting and Unit Testing

on:
  pull_request:
    branches-ignore:
      - production
  workflow_dispatch:
  workflow_call:
    inputs:
      source:
        required: true
        type: string
      reference:
        required: false
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_ACCESS_TOKEN:
        required: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Gesture Firebase

      - name: Install Gesture Firebase dependencies
        run: cd gesture-firebase/functions && npm i

      - name: Compile Gesture Firebase Typescript
        run: cd gesture-firebase/functions && npx tsc

      - name: Run Gesture Firebase ESLint
        run: cd gesture-firebase/functions && npm run lint

      - name: Run Gesture Firebase Unit Tests
        run: cd gesture-firebase/functions && npm test

      # Gesture Firebase User

      - name: Install Gesture Firebase User dependencies
        run: cd gesture-firebase-user/functions && npm i

      - name: Compile Gesture Firebase User Typescript
        run: cd gesture-firebase-user/functions && npx tsc

      - name: Run Gesture Firebase User ESLint
        run: cd gesture-firebase-user/functions && npm run lint

      - name: Run Gesture Firebase User Unit Tests
        run: cd gesture-firebase-user/functions && npm test
