name: Linting and Unit Testing

on:
  pull_request:
    branches-ignore:
      - production
  workflow_dispatch:
  workflow_call:
    inputs:
      source:
        required: true
        type: string
      reference:
        required: false
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_ACCESS_TOKEN:
        required: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Start Containers
        run: docker compose up -d --scale gesture-firebase-compiler=0 --scale gesture-firebase-user-compiler=0 --scale inngest=0

      # Gesture Firebase

      - name: Install Gesture Firebase dependencies
        run: docker compose exec gesture-firebase sh -c "cd functions && npm i"

      - name: Compile Gesture Firebase Typescript
        run: docker compose exec gesture-firebase sh -c "cd functions && npx tsc"

      - name: Run Gesture Firebase ESLint
        run: docker compose exec gesture-firebase sh -c "cd functions && npm run lint"

      - name: Run Gesture Firebase Unit Tests
        run: docker compose exec gesture-firebase sh -c "cd functions && npm test"

      # Gesture Firebase User

      - name: Install Gesture Firebase User dependencies
        run: docker compose exec gesture-firebase-user sh -c "cd functions && npm i"

      - name: Compile Gesture Firebase User Typescript
        run: docker compose exec gesture-firebase-user sh -c "cd functions && npx tsc"

      - name: Run Gesture Firebase User ESLint
        run: docker compose exec gesture-firebase-user sh -c "cd functions && npm run lint"

      - name: Run Gesture Firebase User Unit Tests
        run: docker compose exec gesture-firebase-user sh -c "cd functions && npm test"
