name: Linting and Unit Testing

on:
  pull_request:
    branches-ignore:
      - production
  workflow_dispatch:
  workflow_call:
    inputs:
      source:
        required: true
        type: string
      reference:
        required: false
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        # uses: docker/login-action@v3
        # with:
        #   username: ${{ secrets.DOCKER_USERNAME }}
        #   password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: echo "Login in docker"

      - name: Start Containers
        run: echo "Doing Step"

      # Gesture Firebase

      - name: Install Gesture Firebase dependencies
        run: echo "Doing Step"

      - name: Compile Gesture Firebase Typescript
        run: echo "Doing Step"

      - name: Run Gesture Firebase ESLint
        run: echo "Doing Step"

      - name: Run Gesture Firebase Unit Tests
        run: echo "Doing Step"

      # Gesture Firebase User

      - name: Install Gesture Firebase User dependencies
        run: echo "Doing Step"

      - name: Compile Gesture Firebase User Typescript
        run: echo "Doing Step"

      - name: Run Gesture Firebase User ESLint
        run: echo "Doing Step"

      - name: Run Gesture Firebase User Unit Tests
        run: echo "Doing Step"
