name: Linting and Unit Testing

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        # uses: docker/login-action@v3
        # with:
        #   username: ${{ secrets.DOCKER_USERNAME }}
        #   password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: echo "Logged in to Docker Hub"

      - name: Start Containers
        run: echo "Started Containers"

      # Gesture Firebase

      - name: Install Gesture Firebase dependencies
        run: echo "Install Gesture Firebase dependencies"

      - name: Compile Gesture Firebase Typescript
        run: echo "Compile Gesture Firebase Typescript"

      - name: Run Gesture Firebase ESLint
        run: echo "Run Gesture Firebase ESLint"

      - name: Run Gesture Firebase Unit Tests
        run: echo "Run Gesture Firebase Unit Tests"

      # Gesture Firebase User

      - name: Install Gesture Firebase User dependencies
        run: echo "Install Gesture Firebase User dependencies"

      - name: Compile Gesture Firebase User Typescript
        run: echo "Compile Gesture Firebase User Typescript"

      - name: Run Gesture Firebase User ESLint
        run: echo "Run Gesture Firebase User ESLint"

      - name: Run Gesture Firebase User Unit Tests
        run: echo "Run Gesture Firebase User Unit Tests"
